export const CHANGE_MESSAGE_CC = 'CHANGE_MESSAGE_CC'
export const CHANGE_MESSAGE_BY_PARAM_CC = 'CHANGE_MESSAGE_BY_PARAM_CC'
export const CHANGE_MESSAGE_FC = 'CHANGE_MESSAGE_FC'
export const CHANGE_MESSAGE_BY_PARAM_FC = 'CHANGE_MESSAGE_BY_PARAM_FC'